# Generated by Django 2.2.5 on 2019-10-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recon',
            name='document',
            field=models.FileField(upload_to='recon/data_file'),
        ),
    ]
