# Generated by Django 2.2.5 on 2019-10-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_auto_20191023_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recon',
            name='document',
            field=models.FileField(upload_to='recon/'),
        ),
    ]
